### ISSUE TITLE
Snow cards

### ISSUE THREAD

**Issue by lahatte** [CI-WATER/gsshapy#11]
Alan,

You might want to add these cards to the scripting if they aren't there already.

Clay

-----Original Message-----
From: Follum, Michael L ERDC-RDE-CHL-MS CIV 
Sent: Wednesday, February 08, 2017 7:14 AM
To: Lahatte, Clay W ERDC-RDE-CHL-MS CIV
Subject: RE: Snow in GSSHA

Hey Clay, it does depending on the version.  Here are the cards:

SNOW_SWE_FILE        "SR_SnowWaterEquivalent.swd"
SNOW_SD_FILE            "SR_SnowDepth.sdd"

Mike

-----Original Message-----
From: Lahatte, Clay W ERDC-RDE-CHL-MS CIV 
Sent: Tuesday, February 07, 2017 3:34 PM
To: Follum, Michael L ERDC-RDE-CHL-MS CIV
Cc: Turnbull, Stephen J ERD-MS; Downer, Charles W ERDC-RDE-CHL-MS CIV
Subject: Snow in GSSHA

Mike, does GSSHA output a raster that shows what cells got snow? That would be so nice. I couldn't find a reference to that in the GSSHA wiki.

**Comment by snowman2** [comment]
Is this an issue still?

**Comment by lahatte** [comment]
I don't think so.

Thanks.
Clay


-----Original Message-----
