### ISSUE TITLE
Cannot find path error

### ISSUE THREAD

**Issue by lahatte** [CI-WATER/gsshapy#16]
When I run "activate gssha" the result is...

Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Hawaii\GSSHA\Stream_Attribs\20170316_Thiessen>activate gssha
The system cannot find the path specified.

(gssha) C:\Program Files\Anaconda3\envs\gssha\etc\conda\activate.d>set "GDAL_DRIVER_PATH="

(gssha) Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Hawaii\GSSHA\Stream_Attribs\20170316_Thiessen>

**Comment by snowman2** [comment]
How did you create the conda environment?

**Comment by lahatte** [comment]
As far as I know, I just followed the instructions.


-----Original Message-----

**Comment by snowman2** [comment]
Can you delete it and try again?

**Comment by lahatte** [comment]
It does it on 2 computers.


-----Original Message-----

**Comment by snowman2** [comment]
Try installing the stable release. On windows it only works with Python 2 for now. So, make sure your python environment is Python 2.

```
$ conda create -n gssha python=2
$ activate gssha
(gssha)$ conda install -c conda-forge gsshapy
```

**Comment by lahatte** [comment]
I assume that would be the master version?

Thanks.

-----Original Message-----

**Comment by lahatte** [comment]
I installed the current master gsshapy. It still gives the error. Of course, if you have to activate gssha (where the error is) before installing gsshapy, then it's no surprise the error is still there. :)

Thanks.
Clay


Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Texas\GSSHA\withLake\20170316_Thiessen>activate gssha
The system cannot find the path specified.

(gssha) C:\Program Files\Anaconda3\envs\gssha\etc\conda\activate.d>set "GDAL_DRIVER_PATH="

(gssha) Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Texas\GSSHA\withLake\20170316_Thiessen>



-----Original Message-----

**Comment by snowman2** [comment]
OK. Try removing your old gssha environment:
```
$ conda env remove -n gssha
```
Then, create it again and install gsshapy:
```
$ conda create -n gssha python=2
$ activate gssha
(gssha)$ conda install -c conda-forge gsshapy
```

**Comment by snowman2** [comment]
It is the most-recent release version. Don't worry about installing the master version as they are almost identical at this point.

**Comment by lahatte** [comment]
So do you mean it is the dev version? What is the url to that one? 

Thanks.

-----Original Message-----

**Comment by lahatte** [comment]
Ok. Here's what happens. I do all but the last step. Activate gssha works fine. After the last step activate gssha returns the error.


-----Original Message-----

**Comment by lahatte** [comment]
Now I get this error trying to run the gssha script for the NK projects...

(gssha) Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Texas\GSSHA\withLake\20170316_Thiessen>python Z:\Projects\FY16\Korea_North\Air
Force\AOIs\NK_Texas\rapid_lsm_gssha_framework.py
Traceback (most recent call last):
  File "Z:\Projects\FY16\Korea_North\AirForce\AOIs\NK_Texas\rapid_lsm_gssha_framework.py", line 2, in <module>
    from gridtogssha.framework import GSSHA_WRF_Framework
ImportError: No module named gridtogssha.framework



-----Original Message-----

**Comment by snowman2** [comment]
Woohoo! It worked.

You need to change it to:
```python
from gsshapy.modeling import GSSHAWRFFramework
```

Also, go to: http://gsshapy.readthedocs.io/en/2.2.3/api/modeling/framework.html#gssha-wrf-framework

And scroll to: 'Example with Hotstart' to see some minor changes to input.

**Comment by lahatte** [comment]
Not working. Need better instruction.

Thanks.
Clay


-----Original Message-----
